language: node_js
node_js: 
    - "11.1.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add codecov
  - yarn global add nyc coveralls codeclimate-test-reporter 
script: 
    - yarn && yarn all:test
after_success:
    - codeclimate-test-reporter < ./coverage/lcov.info 
    

