import faker from 'faker';

const userfake = {
  newEvent: {
    name: faker.name.findName(),
    startDate: '2019-05-05',
    endDate: '2019-05-05',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 2,
  },
  newEvent1: {
    name: '',
    startDate: faker.date.future(),
    endDate: faker.date.future(),
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 1,
  },
  newEvent2: {
    name: faker.name.findName(),
    startDate: '',
    endDate: '',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 1,
  },
  newEvent3: {
    name: faker.name.findName(),
    startDate: faker.date.future(),
    endDate: faker.date.future(),
    purpose: faker.lorem.sentences(),
    center: 1,
  },
  newEvent4: {
    name: faker.name.findName(),
    startDate: faker.date.future(),
    endDate: faker.date.future(),
    time: '12:00',
    purpose: '',
    center: 1,
  },
  newEvent5: {
    name: faker.name.findName(),
    startDate: faker.date.future(),
    endDate: faker.date.future(),
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: '',
  },
  newEvent6: {
    name: faker.name.findName(),
    startDate: '2017-10-11',
    endDate: '2017-10-11',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 1,
  },
  newEvent7: {
    name: faker.name.findName(),
    startDate: '2018-10-101',
    endDate: '2018-10-1003',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 1,
  },
  newEvent8: {
    name: faker.name.findName(),
    startDate: '2019-10-11',
    endDate: '2019-10-13',
    time: 'toy',
    purpose: faker.lorem.sentences(),
    center: 1,
  },
  newEvent88: {
    name: faker.name.findName(),
    startDate: '2019-06-05',
    endDate: '2019-06-05',
    time: '12:03',
    purpose: faker.lorem.sentences(),
    center: 'rer',
  },
  newEvent9: {
    name: faker.name.findName(),
    startDate: '2018-06-05',
    endDate: '2018-05-05',
    time: 1,
    purpose: faker.lorem.sentences(),
    center: 9,
  },
  newEvent10: {
    name: faker.name.findName(),
    startDate: '2019-12-01',
    endDate: '2019-12-01',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 2,
  },
  newEvent11: {
    name: faker.name.findName(),
    startDate: '2018-07-05',
    endDate: '2018-07-05',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 1,
  },
  newEvent12: {
    name: faker.name.findName(),
    startDate: '2018-06-15',
    endDate: '2018-06-15',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 2,
  },
  newEvent13: {
    name: faker.name.findName(),
    startDate: '2018-08-05',
    endDate: '2018-08-05',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 2,
  },
  newEvent14: {
    name: faker.name.findName(),
    startDate: '2019-06-05',
    endDate: '2019-06-05',
    time: '12:00',
    purpose: faker.lorem.sentences(),
    center: 2,
  },
};

export default userfake;
